const DataTypes = require('../../dataTypes');
const Property = require('./property');
const PropertyTypes = require('./propertyTypes');
const MaterialTypes = require('./materialTypes');
const ElementTypes = require('./elementTypes');

const defaultProperties = [
  // Generic material properties
  new Property({label: 'lambda', name: 'Linear density', type: PropertyTypes.material, subType: MaterialTypes.generic, dataType: DataTypes.number, siUnit: 'kg/m', siUnitDescription: 'kilogram per meter', minValue: 0.0, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'Linear mass density is the measure of a quantity of any characteristic value per unit of length.'}),
  new Property({label: 'rho', name: 'Density', type: PropertyTypes.material, subType: MaterialTypes.generic, dataType: DataTypes.number, siUnit: 'kg/m3', siUnitDescription: 'kilogram per cubic metre', minValue: 0.0, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'Volumetric mass density, also known as specific mass, of a substance is its mass per unit volume'}),
  new Property({label: 'gamma', name: 'Specific weight', type: PropertyTypes.material, subType: MaterialTypes.generic, dataType: DataTypes.number, siUnit: 'N/m3', siUnitDescription: 'Newton per cubic metre', minValue: 0.0, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'Specific weight, also known as unit weight, is the weight per unit volume of a material. The specific weight of a material is defined as the product of its density and the standard gravity, g (gamma = rho * g = rho * 9.81 m/s2). Unlike density, specific weight is not a fixed property of a material. It depends on the value of the gravitational acceleration, which varies with location'}),

  // Isotropic material properties
  new Property({label: 'E', name: 'Young\'s modulus', type: PropertyTypes.material, subType: MaterialTypes.elasticIsotropic, dataType: DataTypes.number, siUnit: 'GPa,1E9*N/m2', siUnitDescription: 'Giga-Pascals (GPa), 1 Pa = Newton per square metre (N/m2)', minValue: 0.0, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'Young\'s modulus, denoted by E, the Young modulus or the modulus of elasticity in tension, is a mechanical property that measures the tensile stiffness of a solid material. It quantifies the relationship between tensile stress sigma (force per unit area) and axial strain epsilon (proportional deformation) in the linear elastic region of a material and is determined using the formula: E = sigma / epsilon (> 0.0)'}),
  new Property({label: 'G', name: 'Shear modulus', type: PropertyTypes.material, subType: MaterialTypes.elasticIsotropic, dataType: DataTypes.number, siUnit: 'GPa,1E9*N/m2', siUnitDescription: 'Giga-Pascals (GPa), 1 Pa = Newton per square metre (N/m2)', minValue: 0.0, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'Shear modulus or modulus of rigidity, denoted by G, or sometimes S or μ, is a measure of the elastic shear stiffness of a material and is defined as the ratio of shear stress to the shear strain (> 0.0). For elastic isotropic materials: G = E / [2 * (1 + nu)]'}),
  new Property({label: 'nu', name: 'Poisson\'s ratio', type: PropertyTypes.material, subType: MaterialTypes.elasticIsotropic, dataType: DataTypes.number, siUnit: '', siUnitDescription: 'Has no units; it\'s a constant number', minValue: -1.0, includesMinValue: false, maxValue: 0.5, includesMaxValue: false, description: 'Poisson\'s ratio is a measure of the Poisson effect, the deformation (expansion or contraction) of a material in directions perpendicular to the specific direction of loading. The value of Poisson\'s ratio is the negative of the ratio of transverse strain to axial strain. The Poisson\'s ratio of a stable, elasticIsotropic, linear elastic material must be between −1.0 and +0.5 because of the requirement for Young\'s modulus, the shear modulus and bulk modulus to have positive values (-1.0 < NU > 0.5)'}),
  new Property({label: 'alpha', name: 'Coefficient of thermal expansion', type: PropertyTypes.material, subType: MaterialTypes.elasticIsotropic, dataType: DataTypes.number, siUnit: 'T-1', siUnitDescription: 'Inverse of temperature; however, extra dimensions such as cm/cm or mm2/mm2 are added to the unit so that it can be inferred whether the coefficient is linear, area or volumetric.', minValue: Number.MIN_VALUE, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'The coefficient of thermal expansion describes how the size of an object changes with a change in temperature. Specifically, it measures the fractional change in size per degree change in temperature at a constant pressure, such that lower coefficients describe lower propensity for change in size. Several types of coefficients have been developed: volumetric, area, and linear. The choice of coefficient depends on the particular application and which dimensions are considered important. For solids, one might only be concerned with the change along a length, or over some area.'}),

  // Orthotropic material properties
  new Property({label: 'Ea', name: 'a-direction modulus', type: PropertyTypes.material, subType: MaterialTypes.elasticOrthotropic, dataType: DataTypes.number, siUnit: 'GPa,1E9*N/m2', siUnitDescription: 'Giga-Pascals (GPa), 1 Pa = Newton per square metre (N/m2)', minValue: 0.0, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'a-direction modulus (> 0.0)'}),
  new Property({label: 'Eb', name: 'b-direction modulus', type: PropertyTypes.material, subType: MaterialTypes.elasticOrthotropic, dataType: DataTypes.number, siUnit: 'GPa,1E9*N/m2', siUnitDescription: 'Giga-Pascals (GPa), 1 Pa = Newton per square metre (N/m2)', minValue: 0.0, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'b-direction modulus (> 0.0)'}),
  new Property({label: 'Ec', name: 'c-direction modulus', type: PropertyTypes.material, subType: MaterialTypes.elasticOrthotropic, dataType: DataTypes.number, siUnit: 'GPa,1E9*N/m2', siUnitDescription: 'Giga-Pascals (GPa), 1 Pa = Newton per square metre (N/m2)', minValue: 0.0, includesMinValue: true, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'c-direction modulus (> 0.0); Ec=0 is acceptable only for plate elements'}),
  new Property({label: 'nu_ab', name: 'Poisson\'s ratio ab', type: PropertyTypes.material, subType: MaterialTypes.elasticOrthotropic, dataType: DataTypes.number, siUnit: '', siUnitDescription: 'Has no units; constant number', description: 'Poisson\'s ratio that characterizes the transverse strain in the b-direction, when the material is stressed in the a-direction'}),
  new Property({label: 'nu_ac', name: 'Poisson\'s ratio ac', type: PropertyTypes.material, subType: MaterialTypes.elasticOrthotropic, dataType: DataTypes.number, siUnit: '', siUnitDescription: 'Has no units; constant number', description: 'Poisson\'s ratio that characterizes the transverse strain in the c-direction, when the material is stressed in the a-direction'}),
  new Property({label: 'nu_bc', name: 'Poisson\'s ratio bc', type: PropertyTypes.material, subType: MaterialTypes.elasticOrthotropic, dataType: DataTypes.number, siUnit: '', siUnitDescription: 'Has no units; constant number', description: 'Poisson\'s ratio that characterizes the transverse strain in the c-direction, when the material is stressed in the b-direction'}),
  new Property({label: 'Gab', name: 'a-b shear modulus', type: PropertyTypes.material, subType: MaterialTypes.elasticOrthotropic, dataType: DataTypes.number, siUnit: 'GPa,1E9*N/m2', siUnitDescription: 'Giga-Pascals (GPa), 1 Pa = Newton per square metre (N/m2)', minValue: 0.0, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'a-b shear modulus (> 0.0)'}),
  new Property({label: 'Gac', name: 'a-c shear modulus', type: PropertyTypes.material, subType: MaterialTypes.elasticOrthotropic, dataType: DataTypes.number, siUnit: 'GPa,1E9*N/m2', siUnitDescription: 'Giga-Pascals (GPa), 1 Pa = Newton per square metre (N/m2)', minValue: 0.0, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'a-c shear modulus (> 0.0)'}),
  new Property({label: 'Gbc', name: 'b-c shear modulus', type: PropertyTypes.material, subType: MaterialTypes.elasticOrthotropic, dataType: DataTypes.number, siUnit: 'GPa,1E9*N/m2', siUnitDescription: 'Giga-Pascals (GPa), 1 Pa = Newton per square metre (N/m2)', minValue: 0.0, includesMinValue: true, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'b-c shear modulus (> 0.0); Gbc=0 is acceptable only for plate and 2D solid elements'}),
  new Property({label: 'Aa', name: 'a-direction coefficient of thermal expansion', type: PropertyTypes.material, subType: MaterialTypes.elasticOrthotropic, dataType: DataTypes.number, siUnit: 'T-1', siUnitDescription: 'Inverse of temperature; however, extra dimensions such as cm/cm or mm2/mm2 are added to the unit so that it can be inferred whether the coefficient is linear, area or volumetric.', minValue: Number.MIN_VALUE, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'a-direction coefficient of thermal expansion'}),
  new Property({label: 'Ab', name: 'b-direction coefficient of thermal expansion', type: PropertyTypes.material, subType: MaterialTypes.elasticOrthotropic, dataType: DataTypes.number, siUnit: 'T-1', siUnitDescription: 'Inverse of temperature; however, extra dimensions such as cm/cm or mm2/mm2 are added to the unit so that it can be inferred whether the coefficient is linear, area or volumetric.', minValue: Number.MIN_VALUE, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'b-direction coefficient of thermal expansion'}),
  new Property({label: 'Ac', name: 'c-direction coefficient of thermal expansion', type: PropertyTypes.material, subType: MaterialTypes.elasticOrthotropic, dataType: DataTypes.number, siUnit: 'T-1', siUnitDescription: 'Inverse of temperature; however, extra dimensions such as cm/cm or mm2/mm2 are added to the unit so that it can be inferred whether the coefficient is linear, area or volumetric.', minValue: Number.MIN_VALUE, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'c-direction coefficient of thermal expansion'}),

  // Torsion
  new Property({label: 'A', name: 'Cross-section area', type: PropertyTypes.elementGroup, subType: ElementTypes.torsion, dataType: DataTypes.number, siUnit: 'm2', siUnitDescription: 'Square metre (m2)', minValue: 0.0, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'The cross-section area for the torsion element'}),

  // Trusses
  new Property({label: 'A', name: 'Truss cross-section area', type: PropertyTypes.elementGroup, subType: ElementTypes.truss, dataType: DataTypes.number, siUnit: 'm2', siUnitDescription: 'Square metre (m2)', minValue: 0.0, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'The cross-section area for the truss element'}),
  new Property({label: 'Mass', name: 'Mass per unit length', type: PropertyTypes.elementGroup, subType: ElementTypes.truss, dataType: DataTypes.number, siUnit: 'N/m', siUnitDescription: 'Newton per metre (N/m)', minValue: 0.0, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'The truss element mass per unit length'}),
  new Property({label: 'Weight', name: 'Weight per unit length', type: PropertyTypes.elementGroup, subType: ElementTypes.truss, dataType: DataTypes.number, siUnit: 'Kg/m', siUnitDescription: 'Kilogram per metre (Kg/m)', minValue: 0.0, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'The truss element weight per unit length'}),

  // Beams
  new Property({label: 'A', name: 'Beam cross-section area', type: PropertyTypes.elementGroup, subType: ElementTypes.beam, dataType: DataTypes.number, siUnit: 'm2', siUnitDescription: 'Square metre (m2)', minValue: 0.0, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'The cross-section area for the beam element'}),
  new Property({label: 'Mass', name: 'Mass per unit length', type: PropertyTypes.elementGroup, subType: ElementTypes.beam, dataType: DataTypes.number, siUnit: 'N/m', siUnitDescription: 'Newton per metre (N/m)', description: 'The beam element mass per unit length'}),
  new Property({label: 'Weight', name: 'Weight per unit length', type: PropertyTypes.elementGroup, subType: ElementTypes.beam, dataType: DataTypes.number, siUnit: 'Kg/m', siUnitDescription: 'Kilogram per metre (Kg/m)', description: 'The beam element weight per unit length'}),
  new Property({label: 'AS2', name: 'Shear area normal to direction 2', type: PropertyTypes.elementGroup, subType: ElementTypes.beam, dataType: DataTypes.number, siUnit: 'm2', siUnitDescription: 'Square metre (m2)', minValue: 0.0, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'The beam element shear area normal to direction 2'}),
  new Property({label: 'AS3', name: 'Shear area normal to direction 3', type: PropertyTypes.elementGroup, subType: ElementTypes.beam, dataType: DataTypes.number, siUnit: 'm2', siUnitDescription: 'Square metre (m2)', minValue: 0.0, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'The beam element shear area normal to direction 3'}),
  new Property({label: 'I1', name: 'Torsional moment of inertia', type: PropertyTypes.elementGroup, subType: ElementTypes.beam, dataType: DataTypes.number, siUnit: 'Kg*m2', siUnitDescription: 'Kilogram metre squared (Kg*m2)', minValue: 0.0, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'The beam element torsional moment of inertia'}),
  new Property({label: 'I2', name: 'Cross-sectional moment of inertia about the weak axis (axis 2)', type: PropertyTypes.elementGroup, subType: ElementTypes.beam, dataType: DataTypes.number, siUnit: 'Kg*m2', siUnitDescription: 'Kilogram metre squared (Kg*m2)', minValue: 0.0, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'The beam element cross-sectional moment of inertia about the weak axis (axis 2)'}),
  new Property({label: 'I3', name: 'Cross-sectional moment of inertia about the strong axis (axis 3)', type: PropertyTypes.elementGroup, subType: ElementTypes.beam, dataType: DataTypes.number, siUnit: 'Kg*m2', siUnitDescription: 'Kilogram metre squared (Kg*m2)', minValue: 0.0, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'The beam element cross-sectional moment of inertia about the strong axis (axis 3)'}),

  // 2D Solids
  new Property({label: 'Thickness', name: 'Element thickness', type: PropertyTypes.elementGroup, subType: ElementTypes.solid2d, dataType: DataTypes.number, siUnit: 'm', siUnitDescription: 'Metre (m)', minValue: 0.0, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'The default thickness for elements in the group'}),
  new Property({label: 'Angle', name: 'Rotation of principal material axes (1-2) from element axes (X-Y)', type: PropertyTypes.elementGroup, subType: ElementTypes.solid2d, dataType: DataTypes.number, siUnit: 'degrees', siUnitDescription: 'degrees (o)', minValue: Number.MIN_VALUE, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'The rotation of principal material axes (1-2) from element axes (X-Y) (input in degrees; used by elastic orthotropic materials)'}),
  new Property({label: 'Elasticity Conditions', name: 'Elasticity conditions applied to elements in the group', type: PropertyTypes.elementGroup, subType: ElementTypes.solid2d, dataType: DataTypes.number, siUnit: '', siUnitDescription: 'Has no units; constant number', minValue: 1, includesMinValue: true, maxValue: 3, includesMaxValue: true, description: 'Elasticity conditions applied to elements in the group'}),
  new Property({label: 'Stress Reference', name: 'Stress Reference System', type: PropertyTypes.elementGroup, subType: ElementTypes.solid2d, dataType: DataTypes.number, siUnit: '', siUnitDescription: 'Has no units; constant number', minValue: 1, includesMinValue: true, maxValue: 2, includesMaxValue: true, description: 'Indicates the reference system for calculated stresses'}),

  // 3D Solids
  new Property({label: 'Angle', name: 'Rotation of principal material axes (1-2) from element axes (X-Y)', type: PropertyTypes.elementGroup, subType: ElementTypes.solid3d, dataType: DataTypes.number, siUnit: 'degrees', siUnitDescription: 'degrees (o)', minValue: Number.MIN_VALUE, includesMinValue: false, maxValue: Number.MAX_VALUE, includesMaxValue: false, description: 'The rotation of principal material axes (1-2) from element axes (X-Y) (input in degrees; used by elastic orthotropic materials)'}),
  new Property({label: 'Orientation Axes', name: 'Material Orientation Axes', type: PropertyTypes.elementGroup, subType: ElementTypes.solid3d, dataType: DataTypes.string, siUnit: '', siUnitDescription: 'Has no units; constant number', minValue: '', includesMinValue: false, maxValue: '', includesMaxValue: false, description: 'The coordinate system identifier that defines the orientation of the elastic orthotropic material'}),
  new Property({label: 'Stress Reference', name: 'Stress Reference System', type: PropertyTypes.elementGroup, subType: ElementTypes.solid3d, dataType: DataTypes.number, siUnit: '', siUnitDescription: 'Has no units; constant number', minValue: 1, includesMinValue: true, maxValue: 2, includesMaxValue: true, description: 'Indicates the reference system for calculated stresses'}),
];

module.exports = defaultProperties;