# https://docs.github.com/en/actions/guides/building-and-testing-nodejs
# https://docs.github.com/en/actions/guides/about-packaging-with-github-actions
# https://docs.github.com/en/actions/guides/publishing-nodejs-packages

name: Node.js Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
      - run: npm ci
