# https://docs.github.com/en/actions/guides/building-and-testing-nodejs
# https://docs.github.com/en/actions/guides/about-packaging-with-github-actions
# https://docs.github.com/en/actions/guides/publishing-nodejs-packages

name: Node.js Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          always-auth: true
          registry-url: https://registry.npmjs.org
          scope: '@1onlinesolution'
      - name: Install dependencies
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Test
      - run: npm test
        env:
          ENCRYPTION_KEY: ${{secrets.ENCRYPTION_KEY}}
